
[[sec_4]]
== Metadata Features

[[sec_4.1]]
=== Introduction

Meta-features are used to reduce the need to code quality and datum
attributes in individual features, as well as to delimit the extent
of data in the dataset. In a base dataset, some meta-features are
mandatory (<<sec_4.2>>).

Horizontal and vertical uncertainties that apply to the majority of
features are encoded as attributes of one or more *QualityOfNonBathymetricData*
features together covering the same extent as the spatial union of
the *DataCoverage* features in the dataset. (Typically, there would
be one *DataCoverage* feature and one *QualityOfNonBathymetricData*
feature, having the same spatial extent.) Exceptional horizontal and
vertical uncertainties are encoded in a *SpatialAccuracy* information
type associated to particular spatial primitives.

[[sec_4.2]]
=== Mandatory meta features

The mandatory meta features are:

* DataCoverage
* QualityOfNonBathymetricData

[[sec_4.3]]
=== Maximum and minimum display scales

Maximum and minimum values for the display scale attributes are specified
in <<table_4.1>>. These are the same as in S-101 except that the empty
(null) value is not used in S-123.

[[table_4.1]]
.Maximum and minimum display scale values (from S-101 PS)
[cols="2"]
|===
h| maximum display scale h| minimum display scale

| 10,000,000 a| [strike]#empty (null)#
| 3,500,000   | 10,000,000
| 1,500,000   | 3,500,000
| 700,000     | 1,500,000
| 350,000     | 700,000
| 180,000     | 350,000
| 90,000      | 180,000
| 45,000      | 90,000
| 22,000      | 45,000
| 12,000      | 22,000
| 8,000       | 12,000
| 4,000       | 8,000
| 3,000       | 4,000
| 2,000       | 3,000
| 1,000       | 2,000
|===

[[sec_4.4]]
=== Data coverage meta feature

*DataCoverage*: In order to assist in data discovery, the meta feature
*DataCoverage* must be used to provide the area of coverage of the
S-123 dataset. This means that *DataCoverage* expresses where the
presence or absence of S-123 geographic features is asserted. Unlike
S-101 datasets, there is no 'skin of the earth' principle in S-123
and there may be regions covered by a *DataCoverage* but where no
geographic S-123 feature is present.

[cols="a,a,a,a,a",options="unnumbered"]
|===
5+| [underline]#IHO Definition:# A geographical area that describes
the coverage and extent of spatial objects.
5+| *S-10x Metadata Feature: Data Coverage (M_COVR, M_CSCL)*
5+| *[underline]#Super Type:#*
5+| *[underline]#Primitives:# surface*

2+| _Real World_ 2+| _Paper Chart Symbol_ | _ECDIS Symbol_

h| S-123 Attribute h| S-57 Acronym h| Allowable Encoding Value h| Type h| Multiplicity

| Maximum Display Scale       | (CSCALE)          | (see <<table_4.1>>) | IN     | 1, 1
| Minimum Display Scale       |                   | (see <<table_4.1>>) | IN     | 1, 1
| Information                 | (INFORM)          |                     | C      | 0, ++*++
| File Locator                |                   |                     | (S) TE | 0, 1
| File Reference
| (TXTDSC)

(NTXTDS) | | (S) TE | 0, 1
| Headline                    |                   |                     | (S) TE | 0, 1
| Language                    |                   | ISO 639-2/T         | (S) TE | 1, 1
| Text
| (INFORM)

(NINFOM) | | (S) TE | 0, 1
| Interoperability Identifier |                   |                     | UN     | 0, 1

|===

[underline]#INT 1 Reference:#

[[sec_4.4.1]]
==== General

The meta feature *Data Coverage* encodes the area covered by the dataset.
This feature is also used to provide the ECDIS with the scale information
necessary for the determination of dataset loading and unloading in
relation to the user selected viewing scale in the ECDIS. There must
be a minimum of one *Data Coverage* feature in a dataset. *Data Coverage*
features must cover at least the extent of the spatial types in the
dataset, and must not overlap.

The mandatory attribute *maximumDisplayScale* is used to indicate
the largest intended viewing scale for the data. The mandatory attribute
*minimumDisplayScale* is used to indicate the smallest intended viewing
scale for the data. Typically, only a single *DataCoverage* feature
should be used in a dataset. Datasets must have the same value for
*minimumDisplayScale*for all *DataCoverage* features in the dataset.

The use of S-123 data is scale-independent (see <<sec_2.8>>) and maximum
display scale will normally be 1000 (the extreme value in the table
of scales in the S-101 ENC, see Table 4-1). Should a producer need
to encode different maximum and minimum display scales from the extreme
(i.e., create scale-dependent datasets), the values of maximum and
minimum display scales should be harmonized with base layer S-101
datasets.

[underline]#Remarks:#

* This meta feature is intended to support an indication of coverage.
* Where a dataset consists of only one *DataCoverage* feature, the
value for the maximum display scale populated in the dataset discovery
metadata must be the same as the value populated for maximum display
scale on the *DataCoverage*.
* For any *DataCoverage* feature, maximum display scale < minimum
display scale.

[underline]#Distinction:# None

[[sec_4.5]]
=== Quality of Non-Bathymetric Data

[cols="a,a,a,a,a",options="unnumbered"]
|===
5+| [underline]#IHO Definition:# An area within which a uniform assessment
of the quality of the non-bathymetric data exists.
5+| *S-123 Metadata Feature: Quality of Non-Bathymetric Data (M_ACCY)*
5+| *[underline]#Super Type:#*
5+| *[underline]#Primitives:# surface*

2+| _Real World_ 2+| _Paper Chart Symbol_ | _ECDIS Symbol_

h| S-123 Attribute h| S-57 Acronym h| Allowable Encoding Value h| Type h| Multiplicity

| Category of Temporal Variation |
|
1: Extreme Event +
4: Likely to Change +
5: Unlikely to Change
| EN | 0, 1

| Horizontal Distance Uncertainty | (HORACC)         |             | RE     | 0, 1
| Horizontal Position Uncertainty |                  |             | C      | 0, 1
| Uncertainty Fixed               |                  |             | (S) RE | 1, 1
| Uncertainty Variable Factor     |                  |             | (S) RE | 0, 1
| Orientation Uncertainty         |                  |             | RE     | 0, 1
| Survey Date Range               |                  |             | C      | 0, 1
| Date Start                      | (DATSTA)         |             | (S) TD | 0, 1
| Date End                        | (DATEND)         |             | (S) TD | 1, 1
| Vertical Uncertainty
| (SOUACC)

(VERACC) | | C      | 0, 1
| Uncertainty Fixed               |                  |             | (S) RE | 1, 1
| Uncertainty Variable Factor     |                  |             | (S) RE | 0, 1
| Information                     | (INFORM)         |             | C      | 0, ++*++
| File Locator                    |                  |             | (S) TE | 0, 1
| File Reference
| (TXTDSC)

(NTXTDS) | | (S) TE | 0, 1
| Headline                        |                  |             | (S) TE | 0, 1
| Language                        |                  | ISO 639-2/T | (S) TE | 1, 1
| Text
| (INFORM)

(NINFOM) | | (S) TE | 0, 1
| Interoperability Identifier     |                  |             | UN     | 0, 1

|===

[underline]#INT 1 Reference:#

[[sec_4.5.1]]
==== Quality of positions, distances, or directions

The meta feature *Quality of Non-bathymetric Data* may be used to
provide an indication of the overall uncertainty of position, distance,
or direction for all non-bathymetric features. It must not be used
to provide the uncertainty of bathymetric information (which is not
part of the S-123 data model as currently defined anyway) nor should
it be used to delimit peripheral areas where radio reception is uncertain
or variable.

*Positional uncertainty* on the *Quality of Non-bathymetric Data*
applies to non-bathymetric data situated within the area, while
*positional uncertainty* on the associated spatial types qualifies
the location of the *Quality of Non-bathymetric Data* feature itself.

[underline]#Remarks:#

[underline]#Distinction:#
